---
title: "dose_response_test"
author: "Qualia Hooker"
date: "2026-01-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
source("/varidata/research/projects/triche/Lia/master_scripts/r_scripts/dose_response_data/markdowns_scripts/DRC_MASTER.R")
```

```{r}
library(drc)
library(dplyr)
library(tidyr)
library(purrr)
library(ggplot2)
library(ggsci)
```
```{r}
#24 hour data 
raw <- load_data("/varidata/research/projects/triche/Lia/master_scripts/r_scripts/dose_response_data/docs/melphalan_response_data.csv")
agg <- combine_reps(raw)
fits <- fit_all(agg, unique(agg$cell_line))
ic50 <- extract_all(fits, agg_data = agg)
predictions <- pred(fits, agg)
```
```{r}
p1 <- plot_drc(agg, predictions, title = "Melphalan Response",
               colors = scale_colour_nejm())
p2 <- plot_ic50(ic50, title = "Melphalan IC50 Comparison",
                colors = scale_fill_nejm())
p3 <- plot_drc_by_ancestry(agg_data =  agg, predictions, title = "Melphalan Response by Ancestry")
                           
p4 <- plot_box(ic50, title = "Melphalan IC50 Comparison",
                       colors = scale_fill_nejm())

p5 <- plot_violin(ic50, title = "Melphalan IC50 Comparison",
                             colors = scale_fill_nejm())




ggsave("/varidata/research/projects/triche/Lia/master_scripts/r_scripts/dose_response_data/figures/melphalan_drc_24.png", p1, width = 12, height = 8, dpi = 300)
ggsave("/varidata/research/projects/triche/Lia/master_scripts/r_scripts/dose_response_data/figures/melphalan_ic50_24.png", p2, width = 10, height = 6, dpi = 300)
ggsave("/varidata/research/projects/triche/Lia/master_scripts/r_scripts/dose_response_data/figures/melphalan_drc_ancestry_24_updated.png", p3, width = 12, height = 8, dpi = 300)
ggsave("/varidata/research/projects/triche/Lia/master_scripts/r_scripts/dose_response_data/figures/melphalan_ic50_boxplot_24.png", p4, width = 10, height = 6, dpi = 300)
ggsave("/varidata/research/projects/triche/Lia/master_scripts/r_scripts/dose_response_data/figures/melphalan_ic50_violin_24.png", p5, width = 10, height = 6, dpi = 300)

```
```{r}
#run t-test on ic50's
ic50_ttest <- ic50|>
  left_join(agg|>
              select(cell_line,ancestry)|>
              distinct(),
            by = "cell_line")

african_ic50 <- ic50_ttest|>
  filter(ancestry == "African")|>
  pull(Estimate)

european_ic50 <- ic50_ttest|>
  filter(ancestry == "European")|>
  pull(Estimate)

asian_ic50 <- ic50_ttest|>
  filter(ancestry == "East Asian")|>
  pull(Estimate)

t.test(african_ic50, european_ic50)
#	Welch Two Sample t-test

#data:  african_ic50 and european_ic50
#t = 0.84714, df = 1.8981, p-value = 0.4902
#alternative hypothesis: true difference in means is not equal to 0
#95 percent confidence interval:
# -69.17316 100.98014
#sample estimates:
#mean of x mean of y 
# 45.24051  29.33702 
  
t.test(asian_ic50, african_ic50)

aov.test <- ic50_ttest

aov_res <- aov(Estimate ~ ancestry, data = aov.test)
summary(aov_res)
#            Df Sum Sq Mean Sq F value Pr(>F)
#ancestry     2  971.5   485.7   1.378   0.42
#Residuals    2  704.9   352.4        

#post-hoc test
TukeyHSD(aov_res)
#  Tukey multiple comparisons of means
#    95% family-wise confidence level

#Fit: aov(formula = Estimate ~ ancestry, data = aov.test)

#$ancestry
#                         diff       lwr       upr     p adj
#East Asian-African  -37.92171 -173.3639  97.52045 0.4011052
#European-African    -15.90349 -126.4915  94.68457 0.7169413
#European-East Asian  22.01822 -113.4239 157.46037 0.6647484
```
```{r}
#72 hour data
raw_72 <- load_data("/varidata/research/projects/triche/Lia/master_scripts/r_scripts/dose_response_data/docs/melphalan_response_data.csv")
agg_72 <- combine_reps(raw)
fits_72 <- fit_all(agg, unique(agg$cell_line))
ic50_72 <- extract_all(fits)
predictions_72 <- pred(fits, agg)

####PLOTTING FOR 72 HOURS
p1 <- plot_drc(agg, predictions, title = "Melphalan Response",
               colors = scale_colour_nejm())
p2 <- plot_ic50(ic50, title = "Melphalan IC50 Comparison",
                colors = scale_fill_nejm())
p3 <- plot_drc_by_ancestry(agg_data = agg, predictions, title = "Melphalan Response by Ancestry",
                           colors = scale_color_nejm())
p4 <- plot_box(ic50, title = "Melphalan IC50 Comparison",
                       colors = scale_fill_nejm())

p5 <- plot_violin(ic50, title = "Melphalan IC50 Comparison",
                             colors = scale_fill_nejm())




ggsave("/varidata/research/projects/triche/Lia/master_scripts/r_scripts/dose_response_data/figures/melphalan_drc_24.png", p1, width = 12, height = 8, dpi = 300)
ggsave("/varidata/research/projects/triche/Lia/master_scripts/r_scripts/dose_response_data/figures/melphalan_ic50_24.png", p2, width = 10, height = 6, dpi = 300)
ggsave("/varidata/research/projects/triche/Lia/master_scripts/r_scripts/dose_response_data/figures/melphalan_drc_ancestry_24.png", p3, width = 12, height = 8, dpi = 300)
ggsave("/varidata/research/projects/triche/Lia/master_scripts/r_scripts/dose_response_data/figures/melphalan_ic50_boxplot_24.png", p4, width = 10, height = 6, dpi = 300)
ggsave("/varidata/research/projects/triche/Lia/master_scripts/r_scripts/dose_response_data/figures/melphalan_ic50_violin_24.png", p5, width = 10, height = 6, dpi = 300)

####STATS ON 72 HOURS
#run t-test on ic50's
ic50_ttest <- ic50|>
  left_join(agg|>
              select(cell_line,ancestry)|>
              distinct(),
            by = "cell_line")

african_ic50 <- ic50_ttest|>
  filter(ancestry == "African")|>
  pull(Estimate)

european_ic50 <- ic50_ttest|>
  filter(ancestry == "European")|>
  pull(Estimate)

asian_ic50 <- ic50_ttest|>
  filter(ancestry == "East Asian")|>
  pull(Estimate)

t.test(african_ic50, european_ic50)

  
t.test(asian_ic50, african_ic50)

aov.test <- ic50_ttest

aov_res <- aov(Estimate ~ ancestry, data = aov.test)
summary(aov_res)
   

#post-hoc test
TukeyHSD(aov_res)

```



